### ISSUE TITLE
bug in Windows

### ISSUE THREAD

**Issue by yaronha** [v3io/v3io-go#30]
@gtopper @pavius this line make the lib not work in Windows, can we make it generic ?
when i commented out the syscall.S_IFMT and syscall.IP_OFFMASK things worked for me 

https://github.com/v3io/v3io-go/blob/e266c3b72d73fc193c4ecbc64f63bef9f8245621/pkg/dataplane/types.go#L121

**Comment by yaronha** [comment]
@pavius i see its solved in dev branch, any plans to merge ?

**Comment by omesser** [comment]
merged/released since, stale
